---
apps_packages:
  - firefox
  - telegram-desktop
  - github-cli
  - flatpak
  - zenity
  - thunar
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - thunar-volman
  - gvfs
  - gvfs-mtp
  - gvfs-smb
  - gvfs-nfs
  - gvfs-goa
  - file-roller
  - zathura
  - zathura-pdf-mupdf
  - feh
  - transmission-gtk
  - exfatprogs
  - gnome-keyring
  - seahorse
  - gtk3
  - gdk-pixbuf2
  - python-gobject
  - python-imageio
  - python-pillow
  - python-platformdirs
  - ffmpeg
  - python-build
  - python-installer
  - python-setuptools
  - python-wheel
  - python-poetry-core
  - libreoffice-still

apps_waypaper_legacy_pip_packages:
  - waypaper
  - imageio
  - imageio-ffmpeg
  - screeninfo
  - numpy

apps_waypaper_aur_packages:
  - python-screeninfo
  - python-imageio-ffmpeg
  - waypaper

apps_aur_packages:
  - spotify
  - batsignal
  - auto-cpufreq
  - better-control
  - obsidian
  - bitwarden
