"$schema" = "https://mago.carthage.software/1.28.0/schema.json"
version = "1.28"
stack-size = 8388608
threads = 8
php-version = "8.4"
editor-url = "vscode://file/%file%:%line%:%column%"

[source]
includes = ["vendor"]
excludes = [
  ".git/**",
  ".idea/**",
  ".vscode/**",
  ".phpunit.cache/**",
  ".php-cs-fixer.cache",
  ".phpstan.cache/**",
  ".rector/**",
  "bootstrap/cache/**",
  "build/**",
  "cache/**",
  "coverage/**",
  "node_modules/**",
  "public/build/**",
  "storage/**",
  "var/**",
]
extensions = ["php"]

[source.glob]
literal-separator = true
case-insensitive = false
backslash-escape = true
empty-alternates = false

[parser]
enable-short-tags = false

[formatter]
preset = "default"
print-width = 120
tab-width = 4
use-tabs = false
end-of-line = "lf"
single-quote = true
excludes = ["**/Generated/**", "**/generated/**", "**/*Generated.php", "**/*_generated.php"]

[linter]
integrations = ["laravel", "phpunit", "yii"]
baseline-variant = "strict"
minimum-fail-level = "Warning"
excludes = ["database/migrations/**"]

[linter.rules]
ambiguous-constant-access = { enabled = false, level = "Warning" }
ambiguous-function-call = { enabled = false, level = "Warning" }
array-style = { enabled = true, level = "Warning", style = "short" }
assert-description = { enabled = true, level = "Warning" }
assertion-style = { enabled = true, level = "Warning", style = "static" }
block-statement = { enabled = true, level = "Error" }
braced-string-interpolation = { enabled = true, level = "Warning" }
class-name = { enabled = true, level = "Error" }
combine-consecutive-issets = { enabled = true, level = "Warning" }
constant-condition = { enabled = true, level = "Warning" }
constant-name = { enabled = true, level = "Error" }
cyclomatic-complexity = { enabled = false, level = "Error", threshold = 10, method-threshold = 8 }
deprecated-cast = { enabled = true, level = "Error" }
deprecated-shell-execute-string = { enabled = true, level = "Error" }
deprecated-switch-semicolon = { enabled = true, level = "Error" }
disallowed-functions = { enabled = true, level = "Error", functions = [
  "create_function",
  "eval",
  "exec",
  "extract",
  "parse_str",
  "passthru",
  "popen",
  "proc_open",
  "shell_exec",
  "system",
  "unserialize",
] }
disallowed-type-instantiation = { enabled = true, level = "Warning", types = ["DateTime"] }
enum-name = { enabled = true, level = "Error" }
excessive-nesting = { enabled = true, level = "Error", threshold = 4, function-like-threshold = 3 }
excessive-parameter-list = { enabled = true, level = "Error", threshold = 5, constructor-threshold = 8 }
explicit-nullable-param = { enabled = true, level = "Error" }
explicit-octal = { enabled = true, level = "Error" }
file-name = { enabled = true, level = "Warning" }
final-controller = { enabled = true, level = "Error" }
function-name = { enabled = true, level = "Error" }
halstead = { enabled = false, level = "Warning", volume-threshold = 800, difficulty-threshold = 10, effort-threshold = 4000 }
identity-comparison = { enabled = true, level = "Error" }
ineffective-format-ignore-next = { enabled = true, level = "Error" }
ineffective-format-ignore-region = { enabled = true, level = "Error" }
inline-variable-return = { enabled = true, level = "Warning" }
instanceof-stringable = { enabled = true, level = "Warning" }
interface-name = { enabled = true, level = "Error" }
invalid-open-tag = { enabled = true, level = "Error" }
kan-defect = { enabled = false, level = "Error", threshold = 1.4 }
literal-named-argument = { enabled = true, level = "Help" }
loop-does-not-iterate = { enabled = true, level = "Error" }
lowercase-keyword = { enabled = true, level = "Error" }
lowercase-type-hint = { enabled = true, level = "Error" }
middleware-in-routes = { enabled = true, level = "Warning" }
missing-docs = { enabled = true, level = "Warning" }
no-alias-function = { enabled = true, level = "Error" }
no-alternative-syntax = { enabled = true, level = "Error" }
no-array-accumulation-in-loop = { enabled = true, level = "Warning" }
no-assign-in-argument = { enabled = true, level = "Error" }
no-assign-in-condition = { enabled = true, level = "Error" }
no-boolean-flag-parameter = { enabled = true, level = "Warning", exclude-setters = false, exclude-constructors = true }
no-closing-tag = { enabled = true, level = "Error" }
no-db-schema-change = { enabled = true, level = "Error" }
no-dead-store = { enabled = true, level = "Error" }
no-debug-symbols = { enabled = true, level = "Error" }
no-direct-db-query = { enabled = true, level = "Error" }
no-else-clause = { enabled = true, level = "Help" }
no-empty = { enabled = true, level = "Warning" }
no-empty-catch-clause = { enabled = true, level = "Error" }
no-empty-comment = { enabled = true, level = "Warning" }
no-empty-loop = { enabled = true, level = "Error" }
no-error-control-operator = { enabled = true, level = "Error" }
no-eval = { enabled = true, level = "Error" }
no-ffi = { enabled = true, level = "Error" }
no-fully-qualified-global-class-like = { enabled = true, level = "Warning" }
no-fully-qualified-global-constant = { enabled = true, level = "Warning" }
no-fully-qualified-global-function = { enabled = true, level = "Warning" }
no-global = { enabled = true, level = "Error" }
no-goto = { enabled = true, level = "Error" }
no-hash-comment = { enabled = true, level = "Warning" }
no-hash-emoji = { enabled = true, level = "Warning" }
no-inline = { enabled = false, level = "Error" }
no-ini-set = { enabled = true, level = "Error" }
no-insecure-comparison = { enabled = true, level = "Error" }
no-isset = { enabled = true, level = "Warning" }
no-literal-namespace-string = { enabled = true, level = "Warning" }
no-literal-password = { enabled = true, level = "Error" }
no-multi-assignments = { enabled = true, level = "Warning" }
no-negated-ternary = { enabled = true, level = "Error" }
no-nested-ternary = { enabled = true, level = "Error" }
no-noop = { enabled = true, level = "Error" }
no-only = { enabled = true, level = "Error" }
no-parameter-shadowing = { enabled = true, level = "Error" }
no-php-tag-terminator = { enabled = true, level = "Error" }
no-protected-in-final = { enabled = true, level = "Warning" }
no-redundant-block = { enabled = true, level = "Warning" }
no-redundant-continue = { enabled = true, level = "Warning" }
no-redundant-else = { enabled = true, level = "Warning" }
no-redundant-file = { enabled = true, level = "Warning" }
no-redundant-final = { enabled = true, level = "Warning" }
no-redundant-label = { enabled = true, level = "Warning" }
no-redundant-literal-return = { enabled = true, level = "Warning" }
no-redundant-math = { enabled = true, level = "Warning" }
no-redundant-method-override = { enabled = true, level = "Warning" }
no-redundant-nullsafe = { enabled = true, level = "Warning" }
no-redundant-parentheses = { enabled = true, level = "Warning" }
no-redundant-readonly = { enabled = true, level = "Warning" }
no-redundant-string-concat = { enabled = true, level = "Warning" }
no-redundant-use = { enabled = true, level = "Warning" }
no-redundant-variable = { enabled = true, level = "Warning" }
no-redundant-write-visibility = { enabled = true, level = "Warning" }
no-redundant-yield-from = { enabled = true, level = "Warning" }
no-request-all = { enabled = true, level = "Error" }
no-request-variable = { enabled = true, level = "Error" }
no-roles-as-capabilities = { enabled = true, level = "Error" }
no-self-assignment = { enabled = true, level = "Error" }
no-shell-execute-string = { enabled = true, level = "Error" }
no-short-bool-cast = { enabled = true, level = "Error" }
no-short-opening-tag = { enabled = true, level = "Error" }
no-shorthand-ternary = { enabled = true, level = "Error" }
no-side-effects-with-declarations = { enabled = true, level = "Warning", allow-conditional-declarations = true, allow-class-alias = true, allow-class-exists = true }
no-sprintf-concat = { enabled = true, level = "Warning" }
no-trailing-space = { enabled = true, level = "Warning" }
no-underscore-class = { enabled = true, level = "Error" }
no-unescaped-output = { enabled = true, level = "Error" }
no-unsafe-finally = { enabled = true, level = "Error" }
no-unused-closure-capture = { enabled = true, level = "Warning" }
no-unused-global = { enabled = true, level = "Error" }
no-unused-static = { enabled = true, level = "Error" }
no-variable-variable = { enabled = true, level = "Error" }
no-void-reference-return = { enabled = true, level = "Error" }
optional-param-order = { enabled = true, level = "Error" }
prefer-anonymous-migration = { enabled = true, level = "Warning" }
prefer-array-spread = { enabled = true, level = "Warning" }
prefer-arrow-function = { enabled = true, level = "Warning" }
prefer-early-continue = { enabled = true, level = "Warning" }
prefer-explode-over-preg-split = { enabled = true, level = "Warning" }
prefer-first-class-callable = { enabled = true, level = "Warning" }
prefer-interface = { enabled = true, level = "Warning" }
prefer-pre-increment = { enabled = true, level = "Warning" }
prefer-self-return-type = { enabled = true, level = "Warning" }
prefer-static-closure = { enabled = true, level = "Warning" }
prefer-test-attribute = { enabled = true, level = "Warning" }
prefer-view-array = { enabled = true, level = "Warning" }
prefer-while-loop = { enabled = true, level = "Warning" }
property-name = { enabled = true, level = "Error" }
psl-array-functions = { enabled = true, level = "Warning" }
psl-data-structures = { enabled = true, level = "Warning" }
psl-datetime = { enabled = true, level = "Warning" }
psl-math-functions = { enabled = true, level = "Warning" }
psl-output = { enabled = true, level = "Warning" }
psl-randomness-functions = { enabled = true, level = "Warning" }
psl-regex-functions = { enabled = true, level = "Warning" }
psl-sleep-functions = { enabled = true, level = "Warning" }
psl-string-functions = { enabled = true, level = "Warning" }
readable-literal = { enabled = true, level = "Warning" }
require-namespace = { enabled = true, level = "Error" }
require-preg-quote-delimiter = { enabled = true, level = "Error" }
sensitive-parameter = { enabled = true, level = "Error" }
single-class-per-file = { enabled = true, level = "Error" }
sorted-integer-keys = { enabled = true, level = "Warning" }
str-contains = { enabled = true, level = "Warning" }
str-starts-with = { enabled = true, level = "Warning" }
strict-assertions = { enabled = true, level = "Error" }
strict-behavior = { enabled = true, level = "Error" }
strict-types = { enabled = true, level = "Error" }
switch-continue-to-break = { enabled = true, level = "Error" }
tagged-fixme = { enabled = true, level = "Warning" }
tagged-todo = { enabled = true, level = "Warning" }
tainted-data-to-sink = { enabled = true, level = "Error", known-sink-functions = [
  "printf",
  "fprintf",
  "vfprintf",
  "error_log",
  "syslog",
] }
too-many-enum-cases = { enabled = true, level = "Error", threshold = 12 }
too-many-methods = { enabled = true, level = "Error", threshold = 12, count-hooks = true, count-setters-and-getters = true }
too-many-properties = { enabled = true, level = "Error", threshold = 10 }
trait-name = { enabled = true, level = "Error" }
use-compound-assignment = { enabled = true, level = "Warning" }
use-dedicated-expectation = { enabled = true, level = "Warning" }
use-simpler-expectation = { enabled = true, level = "Warning" }
use-specific-assertions = { enabled = true, level = "Warning" }
use-specific-expectations = { enabled = true, level = "Warning" }
use-wp-functions = { enabled = true, level = "Warning" }
valid-docblock = { enabled = true, level = "Error" }
variable-name = { enabled = true, level = "Warning" }
yoda-conditions = { enabled = false, level = "Warning" }

[analyzer]
find-unused-expressions = true
find-unused-definitions = true
find-overly-wide-return-types = true
analyze-dead-code = true
memoize-properties = true
strict-array-index-existence = true
allow-array-truthy-operand = false
check-throws = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true
register-super-globals = true
trust-existence-checks = true
check-property-initialization = true
check-use-statements = true
check-name-casing = true
enforce-class-finality = true
require-api-or-internal = true
check-experimental = true
allow-side-effects-in-conditions = false
allow-implicit-pipe-callable-types = false
class-initializers = ["setUp", "initialize", "boot", "mount"]
unchecked-exceptions = []
unchecked-exception-classes = []

[analyzer.performance]
saturation-complexity-threshold = 16384
disjunction-complexity-threshold = 8192
negation-complexity-threshold = 8192
consensus-limit-threshold = 512
formula-size-threshold = 1024
string-combination-threshold = 256
integer-combination-threshold = 256
array-combination-threshold = 256
loop-assignment-depth-threshold = 4
