---
network_usbguard_mode: audit
network_usbguard_rules: []
network_bluetooth_pairing_timeout_seconds: 180
network_dpi_bypass_provider: spoofdpi
network_spoofdpi_version: "1.3.1"
network_spoofdpi_args: ""
network_spoofdpi_service_enabled: true
