- name: 'Install and configure Greetd Display Manager'
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    wallpaper_file: city-horizon.jpg

  tasks:
    - name: 'Install Display Manager'
      community.general.pacman:
        name:
          - greetd
          - greetd-regreet
        state: present

    - name: 'Create greetd configuration directory'
      ansible.builtin.file:
        path: /etc/greetd
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: 'Enable greetd service'
      ansible.builtin.systemd:
        name: greetd
        enabled: true
        daemon_reload: true

    - name: 'Create Sway configuration for greetd'
      ansible.builtin.copy:
        src: ../../config/greetd/sway-config
        dest: /etc/greetd/sway-config
        owner: root
        group: root
        mode: '0644'

    - name: 'Configure greetd config.toml'
      ansible.builtin.copy:
        src: ../../config/greetd/config.toml
        dest: /etc/greetd/config.toml
        owner: root
        group: root
        mode: '0644'

    - name: 'Copy background image'
      ansible.builtin.copy:
        src: ~/Pictures/Wallpapers/{{ wallpaper_file }}
        dest: /usr/share/backgrounds/{{ wallpaper_file }}
        owner: root
        group: root
        mode: '0644'

    - name: 'Configure ReGreet for Sway'
      ansible.builtin.template:
        src: ../../config/greetd/regreet.toml.j2
        dest: /etc/greetd/regreet.toml
        owner: root
        group: root
        mode: '0644'

    - name: 'Create greeter user'
      ansible.builtin.user:
        name: greeter
        system: true
        shell: /bin/false
        home: /var/lib/greeter
        comment: 'Greeter user'
        create_home: true

    - name: 'Setup state and log directories for regreet'
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: greeter
        group: greeter
        mode: '0755'
      loop:
        - /var/lib/regreet
        - /var/log/regreet
