---
- name: Install Sway core components
  community.general.pacman:
    name:
      - swayidle
      - grim
      - slurp
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - wofi
      - wlogout
      - brightnessctl
    state: present
  become: true
  tags: [packages]

- name: Install swayfx (AUR)
  kewlfft.aur.aur:
    name: swayfx
    state: present
  become: false
  tags: [packages]

- name: Install swaylock-effects (AUR)
  kewlfft.aur.aur:
    name: swaylock-effects
    state: present
  become: false
  tags: [packages]

- name: Install gtklock (AUR)
  kewlfft.aur.aur:
    name: gtklock
    state: present
  become: false
  tags: [packages]
