---
- name: Install Sway core components
  community.general.pacman:
    name:
      - swayidle
      - swaybg
      - grim
      - slurp
      - wl-clipboard
      - cliphist
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - xorg-xwayland
      - libnotify
      - wofi
      - wlogout
      - brightnessctl
      - geoclue
      - tumbler
      - libgepub
      - poppler-glib
      - libgsf
      - libopenraw
      - ffmpegthumbnailer
      - meson
      - ninja
      - playerctl
      - libsoup3
      - polkit
      - polkit-gnome
      - qt5-wayland
      - qt6-wayland
      - swappy
      - wdisplays
      - wf-recorder
      - hyprpicker
    state: present
  become: true
  tags: [desktop, packages]

- name: Install swayfx (AUR)
  kewlfft.aur.aur:
    name: swayfx
    state: present
  become: false
  tags: [desktop, packages]

- name: Install gtklock (AUR)
  kewlfft.aur.aur:
    name: gtklock
    state: present
  become: false
  tags: [desktop, packages]

- name: Install autotiling (AUR)
  kewlfft.aur.aur:
    name: autotiling
    state: present
  become: false
  tags: [desktop, packages]
