---
- name: Check whether Docker CLI is already installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: server_init_docker_cli_stat
  tags:
    - server-init
    - docker
    - packages

- name: Install docker.io
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true
  when: not server_init_docker_cli_stat.stat.exists
  tags:
    - server-init
    - docker
    - packages

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  tags:
    - server-init
    - docker
    - services
