---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  tags: [server-init, firewall, packages]

- name: Allow SSH before enabling ufw
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
  tags: [server-init, firewall, system]

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
  tags: [server-init, firewall, services]
