---
- name: Run apt update and upgrade
  ansible.builtin.include_tasks: update.yml
  when: server_run_update | bool
  tags:
    - server-init
    - update

- name: Install and enable Docker
  ansible.builtin.include_tasks: docker.yml
  when: server_install_docker | bool
  tags:
    - server-init
    - docker

- name: Create dev user
  ansible.builtin.include_tasks: user.yml
  when: server_create_dev_user | bool
  tags:
    - server-init
    - user

- name: Configure ufw firewall
  ansible.builtin.include_tasks: firewall.yml
  when: server_setup_ufw | bool
  tags:
    - server-init
    - firewall

- name: Deploy MTProxy
  ansible.builtin.include_tasks: mtproxy.yml
  when: server_enable_mtproxy | bool
  tags:
    - server-init
    - mtproxy

- name: Install 3x-ui
  ansible.builtin.include_tasks: 3xui.yml
  when: server_enable_3xui | bool
  tags:
    - server-init
    - 3xui

- name: Install monitoring script
  ansible.builtin.include_tasks: monitor.yml
  when: server_enable_monitor | bool
  tags:
    - server-init
    - monitor
