---
- name: Generate MTProxy secret
  ansible.builtin.command:
    cmd: docker run --rm nineseconds/mtg:2 generate-secret --hex {{ server_mtproxy_fake_domain }}
  register: mtg_secret
  changed_when: true
  tags:
    - server-init
    - mtproxy

- name: Stop and remove existing mtproto-proxy container
  community.docker.docker_container:
    name: mtproto-proxy
    state: absent
  tags:
    - server-init
    - mtproxy

- name: Run MTProxy container
  community.docker.docker_container:
    name: mtproto-proxy
    image: nineseconds/mtg:2
    state: started
    restart_policy: unless-stopped
    published_ports:
      - '{{ server_mtproxy_port }}:{{ server_mtproxy_port }}'
    command: >-
      simple-run -n {{ ansible_default_ipv4.address }} -i {{ server_mtproxy_ip_prefer }} 0.0.0.0:{{ server_mtproxy_port }}
      {{ mtg_secret.stdout | trim }}
  tags:
    - server-init
    - mtproxy

- name: Allow MTProxy port in ufw
  community.general.ufw:
    rule: allow
    port: '{{ server_mtproxy_port | string }}'
    proto: tcp
  notify: Reload ufw
  tags:
    - server-init
    - mtproxy

- name: Print MTProxy connection link
  ansible.builtin.debug:
    msg: >-
      https://t.me/proxy?server={{ ansible_default_ipv4.address }}&port={{ server_mtproxy_port }}&secret={{ mtg_secret.stdout | trim }}
  tags:
    - server-init
    - mtproxy
