---
- name: Create dev user with sudo and docker groups
  ansible.builtin.user:
    name: '{{ server_dev_username }}'
    groups:
      - sudo
      - docker
    append: true
    shell: /bin/bash
    create_home: true
    state: present
  tags:
    - server-init
    - user
