# Variables configuration

# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Applications
set $term alacritty --config-file "$HOME/.config/alacritty/alacritty.toml"
set $menu wofi --show=drun --allow-images --allow-markup
set $lock swaylock --config "$HOME/.config/swaylock/config" --clock --image "$HOME/Pictures/Wallpapers/forest-1.jpg" --hide-keyboard-layout
set $menu_clip cliphist list | wofi --dmenu --prompt="📋 Clipboard" --width=45% --height=30% --location=center | cliphist decode | wl-copy
