# Variables configuration

# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Applications
set $term alacritty --config-file "$HOME/.config/alacritty/alacritty.toml"
set $menu wofi --show run
