# Autostart configuration
exec swaync
exec wl-paste --watch cliphist store
exec udiskie --tray

# Workspace startup applications
# exec --no-startup-id swaymsg 'workspace number 1; exec alacritty'
exec --no-startup-id swaymsg 'workspace number 2; exec firefox'
