---
# Laptop (current machine)

hostname: saga
cpu_vendor: amd
gpu_vendor: none
has_battery: true
vpn_profile: laptop


# WireGuard (values from vault)
wg_private_key: "{{ vault_wg_private_key_saga }}"
wg_address: "{{ vault_wg_address_saga }}"
wg_dns: "{{ vault_wg_dns }}"
