model = "gpt-5.5"
web_search = "cached"
personality = "pragmatic"
model_reasoning_effort = "medium"
plan_mode_reasoning_effort = "high"
model_verbosity = "low"
file_opener = "vscode"
default_permissions = "approval-first"
approval_policy = "on-request"
approvals_reviewer = "user"
notify = [
  "notify-send",
  "Codex",
  "Codex needs your attention",
  "-u",
  "normal",
  "-i",
  "dialog-warning",
]
commit_attribution = "Codex <codex@openai.com>"
disable_paste_burst = true
model_reasoning_summary = "none"
hide_agent_reasoning = true

[shell_environment_policy]
inherit = "core"

[analytics]
enabled = false

[feedback]
enabled = false

[features]
multi_agent = true
apps = true
hooks = true
fast_mode = false
shell_snapshot = true
prevent_idle_sleep = true
codex_git_commit = true

[agents]
max_threads = 6
max_depth = 2

[tui]
theme = "catppuccin-mocha"
notifications = true
status_line = ["run-state", "project-name", "git-branch", "model-with-reasoning", "context-remaining", "five-hour-limit", "weekly-limit"]
status_line_use_colors = true

[permissions.approval-first]
extends = ":read-only"
# extends = ":workspace"

[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]

[mcp_servers.github.tools.get_file_contents]
approval_mode = "approve"

[mcp_servers.github.tools.search_code]
approval_mode = "approve"

[mcp_servers.github.tools.list_commits]
approval_mode = "approve"

[mcp_servers.github.tools.search_issues]
approval_mode = "approve"

[mcp_servers.github.tools.get_pull_request_comments]
approval_mode = "approve"

[mcp_servers.github.tools.get_issue]
approval_mode = "approve"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--open-web-dashboard", "False"]

[mcp_servers.serena.tools.write_memory]
approval_mode = "approve"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--browser=firefox"]

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[plugins."github@openai-curated"]
enabled = true

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true
