[main]
background=none

modules=userinfo-module;playerctl-module

time-format=%H:%M
date-format=%A, %d %B %Y

idle-hide=true
idle-timeout=30
start-hidden=false

[userinfo]
round-image=true
horizontal-layout=false
under-clock=false

[playerctl]
position=bottom-center
art-size=125

# [weather]
# position=top-right
# location=auto
# units=metric
# update-interval=1800
