[main]
modules=userinfo-module;playerctl-module

time-format=%H:%M
date-format=%A, %d %B %Y

idle-timeout=30

# Hide on-screen keyboard by default
osk-layout=

# Show input field
input-field=true

[userinfo]
position=top-center
# avatar-path=/var/lib/AccountsService/icons/$USER
show-hostname=true
show-username=true

[playerctl]
position=bottom-center
show-album-art=true
album-art-size=300
show-controls=true
blur-album-art=true
set-wallpaper=true

# [weather]
# position=top-right
# location=auto
# units=metric
# update-interval=1800
