---
all:
  children:
    workstations:
      hosts:
        saga:
          ansible_connection: local
          ansible_host: localhost
        # desktop:
        #   ansible_connection: local
        #   ansible_host: localhost
