---
shell_packages:
  - fish
  - alacritty
  - tmux
  - nodejs

shell_node_global_packages:
  - markdownlint-cli2
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - "@openai/codex"
  - "@prantlf/jsonlint"
  - eslint
  - htmlhint
  - stylelint
  - "@taplo/cli"
  - "@linthtml/linthtml"

shell_configs:
  - { src: fish, dest: "{{ home }}/.config/fish" }
  - { src: alacritty, dest: "{{ home }}/.config/alacritty" }
  - { src: tmux, dest: "{{ home }}/.config/tmux" }
  - { src: shell/aliases, dest: "{{ home }}/.aliases" }
  - { src: .profile, dest: "{{ home }}/.profile" }
  - { src: bash/.bash_profile, dest: "{{ home }}/.bash_profile" }
  - { src: bash/bashrc, dest: "{{ home }}/.bashrc" }
