import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
    {
        ignores: [
            '**/node_modules/**',
            '**/dist/**',
            '**/out/**',
            '**/build/**',
            '**/.git/**',
            '**/coverage/**',
            '**/.cache/**',
            '**/vendor/**',
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        name: 'strict-javascript',
        files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
        languageOptions: {
            ecmaVersion: 2024,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                Buffer: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
            },
        },
        rules: {
            // ─────────────────────────────────────────────────────────────
            // Possible Problems (Error Prevention)
            // ─────────────────────────────────────────────────────────────
            'array-callback-return': ['error', { allowImplicit: false, checkForEach: true }],
            'constructor-super': 'error',
            'for-direction': 'error',
            'getter-return': ['error', { allowImplicit: false }],
            'no-async-promise-executor': 'error',
            'no-await-in-loop': 'warn',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': ['error', 'always'],
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-constructor-return': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-duplicate-imports': ['error', { includeExports: true }],
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-ex-assign': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-import-assign': 'error',
            'no-inner-declarations': ['error', 'both'],
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-obj-calls': 'error',
            'no-promise-executor-return': 'error',
            'no-prototype-builtins': 'error',
            'no-self-assign': ['error', { props: true }],
            'no-self-compare': 'error',
            'no-setter-return': 'error',
            'no-sparse-arrays': 'error',
            'no-template-curly-in-string': 'error',
            'no-this-before-super': 'error',
            'no-undef': 'error',
            'no-unexpected-multiline': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unreachable': 'error',
            'no-unreachable-loop': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
            'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
            'no-unused-private-class-members': 'error',
            'no-unused-vars': [
                'error',
                {
                    vars: 'all',
                    args: 'after-used',
                    ignoreRestSiblings: false,
                    argsIgnorePattern: '^_',
                    caughtErrors: 'all',
                },
            ],
            'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
            'no-useless-backreference': 'error',
            'require-atomic-updates': 'error',
            'use-isnan': 'error',
            'valid-typeof': ['error', { requireStringLiterals: true }],

            // ─────────────────────────────────────────────────────────────
            // Suggestions (Best Practices)
            // ─────────────────────────────────────────────────────────────
            'accessor-pairs': ['error', { enforceForClassMembers: true }],
            'arrow-body-style': ['error', 'as-needed'],
            'block-scoped-var': 'error',
            camelcase: ['error', { properties: 'always', ignoreDestructuring: false }],
            'capitalized-comments': [
                'warn',
                'always',
                {
                    ignoreConsecutiveComments: true,
                    ignoreInlineComments: false,
                },
            ],
            'class-methods-use-this': 'warn',
            complexity: ['warn', { max: 15 }],
            'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
            'consistent-this': ['error', 'self'],
            curly: ['error', 'all'],
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': ['error', { allowKeywords: true }],
            eqeqeq: ['error', 'always', { null: 'always' }],
            'func-name-matching': ['error', 'always'],
            'func-names': ['error', 'as-needed'],
            'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
            'grouped-accessor-pairs': ['error', 'getBeforeSet'],
            'guard-for-in': 'error',
            'id-length': [
                'error',
                { min: 2, max: 40, exceptions: ['i', 'j', 'k', 'x', 'y', 'z', '_'] },
            ],
            'logical-assignment-operators': ['error', 'always'],
            'max-classes-per-file': ['error', { max: 1 }],
            'max-depth': ['warn', { max: 4 }],
            'max-lines': ['warn', { max: 500, skipBlankLines: true, skipComments: true }],
            'max-lines-per-function': [
                'warn',
                { max: 100, skipBlankLines: true, skipComments: true },
            ],
            'max-nested-callbacks': ['warn', { max: 3 }],
            'max-params': ['warn', { max: 4 }],
            'max-statements': ['warn', { max: 20 }, { ignoreTopLevelFunctions: false }],
            'multiline-comment-style': ['warn', 'separate-lines'],
            'new-cap': ['error', { newIsCap: true, capIsNew: false }],
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'warn',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-console': 'warn',
            'no-continue': 'warn',
            'no-delete-var': 'error',
            'no-div-regex': 'error',
            'no-else-return': ['error', { allowElseIf: false }],
            'no-empty': ['error', { allowEmptyCatch: false }],
            'no-empty-function': ['error', { allow: [] }],
            'no-empty-static-block': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-boolean-cast': ['error', { enforceForInnerExpressions: true }],
            'no-extra-label': 'error',
            'no-global-assign': 'error',
            'no-implicit-coercion': [
                'error',
                {
                    boolean: true,
                    number: true,
                    string: true,
                    disallowTemplateShorthand: true,
                },
            ],
            'no-implicit-globals': ['error', { lexicalBindings: true }],
            'no-implied-eval': 'error',
            'no-inline-comments': 'warn',
            'no-invalid-this': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': [
                'warn',
                {
                    ignore: [-1, 0, 1, 2],
                    ignoreArrayIndexes: true,
                    ignoreDefaultValues: true,
                    enforceConst: true,
                },
            ],
            'no-multi-assign': ['error', { ignoreNonDeclaration: false }],
            'no-multi-str': 'error',
            'no-negated-condition': 'warn',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-object-constructor': 'error',
            'no-octal': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': ['error', { props: true }],
            'no-plusplus': ['warn', { allowForLoopAfterthoughts: true }],
            'no-proto': 'error',
            'no-redeclare': ['error', { builtinGlobals: true }],
            'no-regex-spaces': 'error',
            'no-restricted-globals': ['error', 'event', 'fdescribe'],
            'no-return-assign': ['error', 'always'],
            'no-script-url': 'error',
            'no-sequences': ['error', { allowInParentheses: false }],
            'no-shadow': ['error', { builtinGlobals: true, hoist: 'all' }],
            'no-shadow-restricted-names': 'error',
            'no-ternary': 'off',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-undefined': 'off',
            'no-underscore-dangle': ['error', { allowAfterThis: false, allowAfterSuper: false }],
            'no-unneeded-ternary': ['error', { defaultAssignment: false }],
            'no-unused-expressions': [
                'error',
                {
                    allowShortCircuit: false,
                    allowTernary: false,
                    allowTaggedTemplates: false,
                },
            ],
            'no-unused-labels': 'error',
            'no-useless-call': 'error',
            'no-useless-catch': 'error',
            'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
            'no-useless-concat': 'error',
            'no-useless-constructor': 'error',
            'no-useless-escape': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': ['error', { allowAsStatement: false }],
            'no-warning-comments': ['warn', { terms: ['TODO', 'FIXME', 'XXX'], location: 'start' }],
            'no-with': 'error',
            'object-shorthand': ['error', 'always', { avoidQuotes: true }],
            'one-var': ['error', 'never'],
            'one-var-declaration-per-line': ['error', 'always'],
            'operator-assignment': ['error', 'always'],
            'prefer-arrow-callback': ['error', { allowNamedFunctions: false }],
            'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: false }],
            'prefer-destructuring': [
                'error',
                {
                    VariableDeclarator: { array: true, object: true },
                    AssignmentExpression: { array: false, object: false },
                },
                { enforceForRenamedProperties: false },
            ],
            'prefer-exponentiation-operator': 'error',
            'prefer-named-capture-group': 'warn',
            'prefer-numeric-literals': 'error',
            'prefer-object-has-own': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': ['error', { allowEmptyReject: false }],
            'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            radix: ['error', 'always'],
            'require-await': 'error',
            'require-unicode-regexp': 'warn',
            'require-yield': 'error',
            'sort-imports': [
                'error',
                {
                    ignoreCase: false,
                    ignoreDeclarationSort: true,
                    ignoreMemberSort: false,
                    memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
                },
            ],
            'sort-vars': ['warn', { ignoreCase: false }],
            'spaced-comment': ['error', 'always', { exceptions: ['-', '+', '*'] }],
            strict: ['error', 'global'],
            'symbol-description': 'error',
            'vars-on-top': 'error',
            yoda: ['error', 'never', { exceptRange: true }],

            // ─────────────────────────────────────────────────────────────
            // Layout & Formatting (enforce with Prettier when possible)
            // ─────────────────────────────────────────────────────────────
            'array-bracket-newline': ['error', 'consistent'],
            'array-bracket-spacing': ['error', 'never'],
            'array-element-newline': ['error', 'consistent'],
            'arrow-parens': ['error', 'always'],
            'arrow-spacing': ['error', { before: true, after: true }],
            'block-spacing': ['error', 'always'],
            'brace-style': ['error', '1tbs', { allowSingleLine: false }],
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': ['error', { before: false, after: true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['error', 'never'],
            'dot-location': ['error', 'property'],
            'eol-last': ['error', 'always'],
            'func-call-spacing': ['error', 'never'],
            'function-call-argument-newline': ['error', 'consistent'],
            'function-paren-newline': ['error', 'consistent'],
            'generator-star-spacing': ['error', { before: false, after: true }],
            'implicit-arrow-linebreak': ['error', 'beside'],
            indent: ['error', 4, { SwitchCase: 1 }],
            'key-spacing': ['error', { beforeColon: false, afterColon: true }],
            'keyword-spacing': ['error', { before: true, after: true }],
            'line-comment-position': ['warn', { position: 'above' }],
            'linebreak-style': ['error', 'unix'],
            'lines-around-comment': [
                'error',
                {
                    beforeBlockComment: true,
                    beforeLineComment: false,
                    allowBlockStart: true,
                    allowObjectStart: true,
                    allowArrayStart: true,
                    allowClassStart: true,
                },
            ],
            'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
            'max-len': [
                'error',
                {
                    code: 120,
                    tabWidth: 4,
                    ignoreUrls: true,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                    ignoreRegExpLiterals: true,
                },
            ],
            'max-statements-per-line': ['error', { max: 1 }],
            'multiline-ternary': ['error', 'always-multiline'],
            'new-parens': ['error', 'always'],
            'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
            'no-extra-parens': [
                'error',
                'all',
                {
                    conditionalAssign: false,
                    returnAssign: false,
                    nestedBinaryExpressions: false,
                    enforceForArrowConditionals: false,
                },
            ],
            'no-mixed-operators': 'error',
            'no-mixed-spaces-and-tabs': 'error',
            'no-multi-spaces': ['error', { ignoreEOLComments: false }],
            'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1, maxBOF: 0 }],
            'no-tabs': 'error',
            'no-trailing-spaces': ['error', { skipBlankLines: false, ignoreComments: false }],
            'no-whitespace-before-property': 'error',
            'nonblock-statement-body-position': ['error', 'beside'],
            'object-curly-newline': ['error', { consistent: true, multiline: true }],
            'object-curly-spacing': ['error', 'always'],
            'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
            'operator-linebreak': ['error', 'before', { overrides: { '=': 'after' } }],
            'padded-blocks': ['error', 'never'],
            'padding-line-between-statements': [
                'error',
                { blankLine: 'always', prev: '*', next: 'return' },
                { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
                {
                    blankLine: 'any',
                    prev: ['const', 'let', 'var'],
                    next: ['const', 'let', 'var'],
                },
                { blankLine: 'always', prev: 'directive', next: '*' },
                { blankLine: 'any', prev: 'directive', next: 'directive' },
            ],
            'quote-props': ['error', 'as-needed'],
            quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
            'rest-spread-spacing': ['error', 'never'],
            semi: ['error', 'always'],
            'semi-spacing': ['error', { before: false, after: true }],
            'semi-style': ['error', 'last'],
            'space-before-blocks': ['error', 'always'],
            'space-before-function-paren': [
                'error',
                { anonymous: 'always', named: 'never', asyncArrow: 'always' },
            ],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': ['error', { words: true, nonwords: false }],
            'switch-colon-spacing': ['error', { after: true, before: false }],
            'template-curly-spacing': ['error', 'never'],
            'template-tag-spacing': ['error', 'never'],
            'unicode-bom': ['error', 'never'],
            'wrap-iife': ['error', 'inside'],
            'wrap-regex': 'error',
            'yield-star-spacing': ['error', 'after'],
        },
    },
    {
        name: 'typescript-overrides',
        files: ['**/*.ts'],
        rules: {
            'no-undef': 'off',
            'no-unused-vars': 'off',
            'no-shadow': 'off',
            'no-use-before-define': 'off',
            'no-dupe-class-members': 'off',
            'no-useless-constructor': 'off',
            strict: 'off',

            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    vars: 'all',
                    args: 'after-used',
                    ignoreRestSiblings: false,
                    argsIgnorePattern: '^_',
                    caughtErrors: 'all',
                },
            ],
            '@typescript-eslint/no-shadow': ['error', { builtinGlobals: true, hoist: 'all' }],
            '@typescript-eslint/no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
        },
    },
];
