# Variables configuration

# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Applications
set $term alacritty --config-file "$HOME/.config/alacritty/alacritty.toml"
set $menu wofi --show=drun --allow-images --allow-markup
set $lock gtklock
set $file_manager thunar
set $menu_clip cliphist list | wofi --dmenu --prompt="📋 Clipboard" --width=45% --height=30% --location=center | cliphist decode | wl-copy

# System utilities
set $notification_daemon swaync
set $notification_client swaync-client
set $osd_server swayosd-server
set $osd_client swayosd-client
set $clipboard_manager cliphist
set $wallpaper_manager waypaper
set $idle_manager swayidle

# Screenshot utilities
set $screenshot_tool grim
set $screenshot_selector slurp
set $screenshot_editor swappy
set $screenshot_dir ~/Pictures/Screenshots

# Media utilities
set $volume_control $osd_client
set $brightness_control brightnessctl
set $media_control playerctl
