#!/usr/bin/env bash

# Check if Docker daemon is running
if ! systemctl is-active --quiet docker; then
    # Docker daemon is not running - hide the module
    echo '{"text": "", "tooltip": "Docker daemon is not running", "class": "hidden"}'
    exit 0
fi

# Get the number of running containers
running_containers=$(docker ps --format "table {{.Names}}" 2>/dev/null | wc -l)

# Subtract the table header
if [ "$running_containers" -gt 0 ]; then
    running_containers=$((running_containers - 1))
fi

# If there are no containers, hide the module
if [ "$running_containers" -eq 0 ]; then
    echo '{"text": "0", "tooltip": "No running Docker containers", "class": "stopped"}'
    exit 0
fi

# Get the list of running containers for tooltip
container_list=$(docker ps --format "{{.Names}} ({{.Image}})" 2>/dev/null | head -10)

# If there are more than 10 containers, add a note
total_containers=$(docker ps --format "{{.Names}}" 2>/dev/null | wc -l)
if [ "$total_containers" -gt 10 ]; then
    container_list="$container_list\n... and $((total_containers - 10)) more"
fi

# Format the output
# shellcheck disable=SC2086
# shellcheck disable=SC2028
echo '{"text": "'$running_containers'", "tooltip": "Running containers:\n'$container_list'", "class": "running"}'
