---
- name: rebuild initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
  become: true
  changed_when: true

- name: regenerate grub config
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
  changed_when: true
