---
desktop_configs:
  - src: sway
    dest: '{{ home }}/.config/sway'
  - src: wofi
    dest: '{{ home }}/.config/wofi'
  - src: swaync
    dest: '{{ home }}/.config/swaync'
  - src: swayosd
    dest: '{{ home }}/.config/swayosd'
  - src: swayidle
    dest: '{{ home }}/.config/swayidle'
  - src: swappy
    dest: '{{ home }}/.config/swappy'
  - src: waypaper
    dest: '{{ home }}/.config/waypaper'
  - src: wlogout
    dest: '{{ home }}/.config/wlogout'
  - src: zathura
    dest: '{{ home }}/.config/zathura'

desktop_waybar_files:
  - src: scripts
    dest: '{{ home }}/.config/waybar/scripts'
  - src: style.css
    dest: '{{ home }}/.config/waybar/style.css'
  - src: mocha.css
    dest: '{{ home }}/.config/waybar/mocha.css'
