---
- name: Install bluetooth packages
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - blueman
      - network-manager-applet
    state: present
  become: true
  tags: [network, packages]

- name: Deploy bluetooth config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/roles/network/files/bluetooth/main.conf"
    dest: /etc/bluetooth/main.conf
    state: link
    force: true
  become: true
  tags: [network, system]

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
  become: true
  tags: [network, services]
