---
- name: Install firewall
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags: [network]
  tags: [network, firewall]

- name: Configure Bluetooth
  ansible.builtin.include_tasks:
    file: bluetooth.yml
    apply:
      tags: [network]
  tags: [network, bluetooth]

- name: Configure WireGuard
  ansible.builtin.include_tasks:
    file: wireguard.yml
    apply:
      tags: [network]
  tags: [network, wireguard]

- name: Configure sing-box
  ansible.builtin.include_tasks:
    file: sing-box.yml
    apply:
      tags: [network]
  tags: [network, sing-box]

- name: Deploy VPN management script
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/roles/network/scripts/vpn"
    dest: "{{ home }}/.local/bin/vpn"
    state: link
    force: true
  tags: [network, config]

- name: Deploy geoclue config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/roles/network/files/geoclue/curl.conf"
    dest: "{{ home }}/.config/geoclue/curl.conf"
    state: link
    force: true
  tags: [network, config]
