---
audio_packages:
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - pavucontrol

multimedia_packages:
  - ffmpeg
  - vlc
  - mpv
  - imagemagick

audio_configs:
  - { src: pipewire, dest: "{{ ansible_env.HOME }}/.config/pipewire" }
  - { src: wireplumber, dest: "{{ ansible_env.HOME }}/.config/wireplumber" }
