---
editor_packages:
  - neovim
  - code

editor_configs:
  - { src: nvim, dest: "{{ ansible_env.HOME }}/.config/nvim" }
  - { src: code/code-flags.conf, dest: "{{ ansible_env.HOME }}/.config/code-flags.conf" }
  - { src: git/gitconfig, dest: "{{ ansible_env.HOME }}/.gitconfig" }
