---
desktop_configs:
  - { src: sway, dest: "{{ ansible_env.HOME }}/.config/sway" }
  - { src: waybar, dest: "{{ ansible_env.HOME }}/.config/waybar" }
  - { src: wofi, dest: "{{ ansible_env.HOME }}/.config/wofi" }
  - { src: swaync, dest: "{{ ansible_env.HOME }}/.config/swaync" }
  - { src: swayosd, dest: "{{ ansible_env.HOME }}/.config/swayosd" }
  - { src: swayidle, dest: "{{ ansible_env.HOME }}/.config/swayidle" }
  - { src: swappy, dest: "{{ ansible_env.HOME }}/.config/swappy" }
  - { src: waypaper, dest: "{{ ansible_env.HOME }}/.config/waypaper" }
  - { src: wlogout, dest: "{{ ansible_env.HOME }}/.config/wlogout" }
  - { src: zathura, dest: "{{ ansible_env.HOME }}/.config/zathura" }
