---
- name: Install PHP
  community.general.pacman:
    name:
      - php
      - composer
      - xdebug
    state: present
  become: true
  tags:
    - development
    - packages

- name: Deploy xdebug config
  ansible.builtin.file:
    src: '{{ dotfiles_dir }}/roles/development/files/tools/php/xdebug/xdebug.ini'
    dest: /etc/php/conf.d/xdebug.ini
    state: link
    force: true
  become: true
  tags:
    - development
    - config

- name: Install global Composer packages
  community.general.composer:
    command: require
    global_command: true
    arguments: '{{ item }}'
  loop:
    - phpstan/phpstan
    - phpstan/extension-installer
    - phpstan/phpstan-strict-rules
    - phpstan/phpstan-deprecation-rules
    - rector/rector
    - driftingly/rector-laravel
    - friendsofphp/php-cs-fixer
    - squizlabs/php_codesniffer
    - slevomat/coding-standard
    - devstrict/phpcs:dev-main
    - phpcompatibility/php-compatibility:"^10.0.0@dev"
    - phpmd/phpmd
    - carthage-software/mago
  become: false
  ignore_errors: '{{ ansible_check_mode }}'
  tags:
    - development
    - packages
