---
extends: default

rules:
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  comments-indentation: enable
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
    ignore-shebangs: true

  document-start:
    present: true

  truthy:
    allowed-values:
      - 'true'
      - 'false'
      - 'yes'
      - 'no'
    check-keys: true

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true

  key-duplicates: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix

  trailing-spaces: enable

  quoted-strings:
    quote-type: single
    required: only-when-needed
    check-keys: false

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
