---
- name: Remove conflicting exfat-utils before installing exfatprogs
  community.general.pacman:
    name: exfat-utils
    state: absent
  become: true
  tags: [apps, packages]

- name: Install applications
  community.general.pacman:
    name: "{{ apps_packages }}"
    state: present
  become: true
  tags: [apps, packages]

- name: Install AUR applications
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: false
  loop: "{{ apps_aur_packages }}"
  loop_control:
    label: "{{ item }}"
  tags: [apps, packages]

- name: Enable auto-cpufreq service
  ansible.builtin.systemd:
    name: auto-cpufreq
    enabled: true
    state: started
  become: true
  when: has_battery | default(false)
  tags: [apps, services]

- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
  tags: [apps, packages]

- name: Install custom waypaper
  ansible.builtin.pip:
    name: "git+https://github.com/vix-4800/waypaper.git"
    state: present
    extra_args: "--break-system-packages --no-deps"
  become: true
  tags: [apps, packages]
