#!/usr/bin/env bash

NMCLI_OUTPUT=$(nmcli c show --active 2>/dev/null | grep wg0)

if [[ -n "${NMCLI_OUTPUT}" ]]; then
    echo '{"text": "󰦝", "class": "connected", "tooltip": "VPN Connected"}'
else
    echo '{"text": "󰦞", "class": "disconnected", "tooltip": "VPN Disconnected"}'
fi
