- name: "Setup Arch"
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: "Upgrade all packages"
      community.general.pacman:
        update_cache: yes
        upgrade: yes
