---
# Services enabled on all hosts
services_common:
  - alsa-restore.service
  - xdg-user-dirs.service
  - break-reminder.timer
  - water-reminder.timer
  - posture-check.timer
  - composer-update-check.timer
  - dotfiles-update-check.timer
  - git-maintenance@daily.timer
  - git-maintenance@hourly.timer
  - git-maintenance@weekly.timer
  - arch-audit.timer

# Additional services per host (merged in tasks)
services_host: []
