- name: 'Install editors'
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: 'Install Neovim'
      community.general.pacman:
        name:
          - neovim
        state: present

    - name: 'Check if yay is installed'
      ansible.builtin.command:
        cmd: which yay
      register: yay_check
      changed_when: false
      failed_when: false

    - name: 'Install Visual Studio Code from AUR'
      become: false
      kewlfft.aur.aur:
        use: yay
        name:
          - visual-studio-code-bin
        state: present
      when: yay_check.rc == 0
