- name: 'Configure system environment'
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: 'Configure environment variables'
      ansible.builtin.copy:
        src: ../config/environment/environment
        dest: /etc/environment
        owner: root
        group: root
        mode: '0644'

    - name: 'Enable wheel group in sudoers'
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wheel-group
        content: |
          %wheel ALL=(ALL:ALL) ALL
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: 'Add user to wheel group'
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: wheel
        append: true
