- name: 'Configure system environment'
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    gpu_type: nvidia # nvidia | amd | intel | hybrid | none — override with --extra-vars gpu_type=amd
  tasks:
    - name: 'Configure base environment variables'
      ansible.builtin.copy:
        src: ../config/environment/environment
        dest: /etc/environment
        owner: root
        group: root
        mode: '0644'

    - name: 'Add NVIDIA Wayland environment variables'
      ansible.builtin.blockinfile:
        path: /etc/environment
        marker: '# {mark} NVIDIA WAYLAND SUPPORT (managed by ansible)'
        block: |
          __GLX_VENDOR_LIBRARY_NAME=nvidia
          WLR_NO_HARDWARE_CURSORS=1
          LIBVA_DRIVER_NAME=nvidia
          NVD_BACKEND=direct
      when: gpu_type == 'nvidia'

    - name: 'Remove NVIDIA Wayland environment variables'
      ansible.builtin.blockinfile:
        path: /etc/environment
        marker: '# {mark} NVIDIA WAYLAND SUPPORT (managed by ansible)'
        block: ''
        state: absent
      when: gpu_type != 'nvidia'

    - name: 'Enable wheel group in sudoers'
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wheel-group
        content: |
          %wheel ALL=(ALL:ALL) ALL
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: 'Add user to wheel group'
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: wheel
        append: true
