- name: 'Install essential packages'
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: 'Install essential packages'
      community.general.pacman:
        name:
          - base-devel
          - git
          - curl
          - jq
          - make
          - less
          - unzip
          - gcc
          - udiskie
          - ffmpeg
          - man
          - wget
        state: present

    - name: 'Install modern CLI tools'
      community.general.pacman:
        name:
          - eza
          - bat
          - ripgrep
          - fd
          - tldr
          - chafa
          - reflector
        state: present

    - name: 'Update mirror list with reflector'
      ansible.builtin.command:
        cmd: reflector --country 'Russia' --latest 10 --age 24 --sort rate --save /etc/pacman.d/mirrorlist
      changed_when: false
