- name: 'Install fonts'
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: 'Install fonts'
      community.general.pacman:
        name:
          - ttf-jetbrains-mono-nerd
          - otf-font-awesome
          - woff2-font-awesome
          - ttf-dejavu
          - ttf-liberation
          - noto-fonts
          - noto-fonts-emoji
          - ttf-opensans
          - ttf-roboto
          - ttf-ubuntu-font-family
          - inter-font
          - freetype2
          - fontconfig
        state: present
