- name: 'Install applications'
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: 'Install applications'
      become: true
      community.general.pacman:
        name:
          - firefox
          - discord
          - telegram-desktop
          - vlc
          - obsidian
          - wireguard-tools
          - github-cli
          - flatpak
          - zathura
          - zathura-pdf-mupdf
          - thunar
          - thunar-archive-plugin
          - thunar-media-tags-plugin
          - thunar-shares-plugin
          - thunar-vcs-plugin
          - tumbler
          - ffmpegthumbnailer
          - gvfs
          - gvfs-mtp
          - gvfs-smb
          - gvfs-nfs
          - feh
          - trash-cli
        state: present

    - name: 'Check if yay is installed'
      ansible.builtin.command:
        cmd: which yay
      register: yay_check
      changed_when: false
      failed_when: false

    - name: 'Install AUR applications'
      kewlfft.aur.aur:
        use: yay
        name:
          - spotify
          - catppuccin-gtk-theme-mocha
          - wdisplays
          - swappy
          - better-control-git
          - swayosd
          - batsignal
          - auto-cpufreq
          - betterdiscord-installer
        state: present
      when: yay_check.rc == 0
      become: true
      become_user: aur_builder

    - name: 'Enable and start services for AUR applications'
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      when: yay_check.rc == 0
      loop:
        - auto-cpufreq
