# True color settings
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
bind C-a send-prefix

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left-length 40
set -g status-right-length 90
set -g status-interval 5

set -g status-keys vi

set -g window-status-current-format "#[fg=colour10]#I #[fg=colour15]#W #[fg=colour8]#F"

bind r source-file ~/.tmux.conf

setw -g clock-mode-colour yellow
